In [1]:
import numpy as np

In [17]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = complex)

In [43]:
arr

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [45]:
zeros = np.zeros((2,3))     # default dtype - float
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
zeros = np.zeros((2,3), dtype=np.int32)    # dtype - integer(int32)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [49]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
ones = np.ones((3,3), dtype = np.int32)
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [60]:
# traverse all elements
arr = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = np.int32)
for i in arr:         #rows
    for j in i:      #columns
        print(j, end = " ")
    print()    #print new line

1 2 3 
4 5 6 
7 8 9 


In [78]:
# addition of two matrices
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = np.int32)
m2 = np.array([[10,20,30],[40,50,60],[70,80,90]], dtype = np.int32)

result = []
for i in range(len(m1)):
    row = []
    for j in range(len(m1[0])):
        row.append(m1[i][j]+m2[i][j])
    result.append(row)
#print(result)
for i in result:
    for j in i:
        print(j, end = " ")
    print()

11 22 33 
44 55 66 
77 88 99 


In [82]:
# addition of two matrices using numpy
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = np.int32)
m2 = np.array([[10,20,30],[40,50,60],[70,80,90]], dtype = np.int32)
print("Result : ",m1+m2)

Result :  [[11 22 33]
 [44 55 66]
 [77 88 99]]


In [84]:
# multiplication of two matrices using numpy
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = np.int32)
m2 = np.array([[10,20,30],[40,50,60],[70,80,90]], dtype = np.int32)
result = np.dot(m1,m2)
print("Result : ",result)

Result :  [[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


In [86]:
# transpose of a matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
transpose = np.transpose(matrix)
transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])